#spring:
#  datasource:
#    generate-unique-name: false
#    name: tacocloud
#  jpa:
#    show-sql: true
spring:
  data:
    cassandra:
      keyspace-name: taco_cloud
      schema-action: recreate
      local-datacenter: datacenter1
      username: tacocloud
      password: taco123